### ISSUE TITLE
Inquiry about Safe Stiffness Parameters and Oscillation Issues

### ISSUE THREAD

**Issue by Cody-Vu** [matthias-mayr/Cartesian-Impedance-Controller#30]
Hello everyone,

I am currently working with the Cartesian impedance controller with MoveIt and have encountered some challenges while tuning the stiffness parameters. I've been experimenting with different values to achieve accurate pose control.

Specifically, I observed that with lower stiffness parameters, the robot struggled to accurately reach the desired pose, especially the orientation. When I increased the stiffness values to (1000, 1000, 1000, 250, 250, 250) for translation and rotation respectively, the pose accuracy improved, but the robot started to exhibit significant oscillations towards the end of the motion. 

Given the expertise of the contributors to this project, I was wondering if you might have any recommended stiffness parameters that are known to be safe and effective. Maybe maximum and minimum values that you would recommend. It would be very helpful to know if you have identified any rules of thumb for balancing translational and rotational stiffness. Also, I am curious to know if you have encountered similar oscillation issues during your tests and how you resolved them.

Thank you very much for your time and assistance. Any insights you can provide would be greatly appreciated.

Additional Information:

High stiffness values: (1000, 1000, 1000, 250, 250, 250)
Observed behavior:
Low stiffness: Inaccurate pose, especially orientation
High stiffness: Accurate pose, but significant oscillations at the end of motion
I'm looking for guidance on:

- Safe and effective stiffness parameters
- Rules of thumb for balancing translational and rotational stiffness
- Experiences with similar oscillation issues and solutions
- Is it possible to test this controller in Gazebo? If so, does anyone have a guide or instructions on how to set up the simulation?
Thank you!

**Comment by matthias-mayr** [comment]
When I used it, I generally usually did not go over 800 translational stiffness and my general rule of thumb was to use 1/10 of the translational stiffness for the rotational stiffness.  We had the controller running on a Franka Emika Robot (Panda) though, but also with lower stiffnesses than you are running right now.

One thing you can experiment with is to change the damping. By default it is [critically damped with 2*sqrt(stiffness)](https://github.com/matthias-mayr/Cartesian-Impedance-Controller/blob/3c6b61697b67366b05dea9661527310c4bd972ef/src/cartesian_impedance_controller.cpp#L325C1-L326C12) and that was enough for what I ran, but you can experiment with increasing this.

> Is it possible to test this controller in Gazebo? If so, does anyone have a guide or instructions on how to set up the simulation?

Yes, you can run this controller just as well in Gazebo. The only thing you need to do is to make your simulated robot load this controller. I used this for most of the development and the unit tests in this repo run the robot in simulation as well.

Generally, you will always experience some deviations due to friction and stiction of the robot hardware. We have [conducted a master thesis](https://lup.lub.lu.se/student-papers/search/publication/9136576) to improve the tracking accuracy. Feel free to have a look.

**Comment by Cody-Vu** [comment]
@matthias-mayr , first of all thank you very much for your response. I will stick with 800 as maximum values and 1/10 for the damping values for now. I haven't managed to load the controller in gazebo.

When I start gazebo I receive this error:

[INFO] [1744209259.960251, 0.016000]: Loading controller: CartesianImpedance_trajectory_controller
[ERROR] [1744209259.971801754, 0.022000000]: Could not load controller 'CartesianImpedance_trajectory_controller' because the type was not specified. Did you load the controller configuration on the parameter server (namespace: '/CartesianImpedance_trajectory_controller')?

Probably I am loading the controller incorrect. Basically in `demo_gazebo.launch` in the `panda_moveit_config` package I changed the default controller (effort) to `CartesianImpedance_trajectory_controller`:

```
<?xml version="1.0"?>
<launch>
  <!-- MoveIt options -->
  <arg name="pipeline" default="ompl" doc="Planning pipeline to use with MoveIt"/>

  <!-- Panda options -->
  <arg name="load_gripper" default="true" />
  <arg name="transmission" default="CartesianImpedance" />

  <!-- Gazebo options -->
  <arg name="gazebo_gui" default="true" doc="Start Gazebo GUI"/>
  <arg name="paused" default="false" doc="Start Gazebo paused"/>

  <!-- Launch the gazebo simulator and spawn the robot -->
  <include file="$(find franka_gazebo)/launch/panda.launch" pass_all_args="true">
    <arg name="headless" value="$(eval not arg('gazebo_gui'))" />
    <arg name="use_gripper" default="$(arg load_gripper)" />
    <arg name="controller" default="$(arg transmission)_trajectory_controller" />
  </include>

  <!-- Launch MoveIt -->
  <include file="$(dirname)/demo.launch" pass_all_args="true">
    <!-- robot_description is loaded by gazebo.launch, to enable Gazebo features -->
    <arg name="load_robot_description" value="false" />
    <!-- MoveItSimpleControllerManager provides ros_control's JointTrajectory controllers
         as well as GripperCommand actions -->
    <arg name="moveit_controller_manager" value="simple" />
  </include>
</launch>
```

As this launch file uses the `simple_moveit_controller_manager` I changed the controller list in `simple_moveit_controllers.yaml` to:

```
controller_list:
  - name: panda_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
```

And in addition I added the parameters to `default_controllers.yaml` (franka_ros/franka_control/config) and `gazebo_controllers.yaml` (panda_moveit_config/config) (because I was not sure):
```
CartesianImpedance_trajectory_controller:
  type: cartesian_impedance_controller/CartesianImpedanceController
  joints:                               # Joints to control
    - $(arg arm_id)_joint1
    - $(arg arm_id)_joint2
    - $(arg arm_id)_joint3
    - $(arg arm_id)_joint4
    - $(arg arm_id)_joint5
    - $(arg arm_id)_joint6
    - $(arg arm_id)_joint7
  end_effector: panda_link8            # Link to control arm in
  update_frequency: 500                 # Controller update frequency in Hz
  # Optional parameters - the mentioned values are the defaults
  dynamic_reconfigure: true             # Starts dynamic reconfigure server
  handle_trajectories: true             # Accept traj., e.g. from MoveIt
  robot_description: /robot_description # In case of a varying name
  wrench_ee_frame: panda_link8         # Default frame for wrench commands
  delta_tau_max: 1.0                    # Max. commanded torque diff between steps in Nm
  filtering:                            # Update existing values (0.0 1.0] per s
    nullspace_config: 0.1               # Nullspace configuration filtering
    pose: 0.1                           # Reference pose filtering
    stiffness: 0.1                      # Cartesian and nullspace stiffness
    wrench: 0.1                         # Commanded torque
  verbosity:
    verbose_print: false                # Enables additional prints
    state_msgs: false                   # Messages of controller state
    tf_frames: false                    # Extra tf frames
```
Am I doing it wrong? I haven't found any information on how to switch controllers in gazebo. And this approach at least worked with standard controllers (switching from effort to position for example). On the real robot I can switch them with the controller_manager but not in gazebo. I'd appreciate if you can clarify how to load the cartesian impedance controller correctly. Thanks in advance!
